name = "v60"
pages_build_output_dir = ".open-next"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "v60-db"
database_id = "764a554d-9c33-44b1-9fe0-d524d0f6df43"
migrations_dir = "prisma/migrations"

[observability]
enabled = true
