-- BrewForce Oracle Schema
-- Standard types for Oracle Autonomous Database

-- RECIPES Table
CREATE TABLE RECIPES (
    id VARCHAR2(36) PRIMARY KEY,
    user_id VARCHAR2(255) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    method VARCHAR2(100) NOT NULL,
    coffee_grams NUMBER NOT NULL,
    water_grams NUMBER NOT NULL,
    ice_grams NUMBER DEFAULT 0,
    ratio NUMBER NOT NULL,
    grind_size VARCHAR2(100) NOT NULL,
    temperature NUMBER NOT NULL,
    bean_origin VARCHAR2(255),
    ai_generated NUMBER(1) DEFAULT 0,
    notes CLOB,
    rating NUMBER DEFAULT 0,
    rating_count NUMBER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- BREW_STAGES Table
CREATE TABLE BREW_STAGES (
    id VARCHAR2(36) PRIMARY KEY,
    recipe_id VARCHAR2(36) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    target_weight NUMBER NOT NULL,
    target_seconds NUMBER NOT NULL,
    temperature NUMBER NOT NULL,
    action VARCHAR2(50) DEFAULT 'none',
    notes CLOB,
    CONSTRAINT fk_stage_recipe FOREIGN KEY (recipe_id) REFERENCES RECIPES (id) ON DELETE CASCADE
);

-- BREW_SESSIONS Table
CREATE TABLE BREW_SESSIONS (
    id VARCHAR2(36) PRIMARY KEY,
    user_id VARCHAR2(255) NOT NULL,
    recipe_id VARCHAR2(36),
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    final_weight NUMBER NOT NULL,
    history_json CLOB,
    sensory_feedback CLOB,
    CONSTRAINT fk_session_recipe FOREIGN KEY (recipe_id) REFERENCES RECIPES (id) ON DELETE SET NULL
);

-- SHARED_RECIPES Table
CREATE TABLE SHARED_RECIPES (
    token_id VARCHAR2(255) PRIMARY KEY,
    data CLOB NOT NULL,
    share_chain CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP
);

-- METRICS Table
CREATE TABLE METRICS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event VARCHAR2(255) NOT NULL,
    anon_id VARCHAR2(255),
    token_id VARCHAR2(255),
    local_id VARCHAR2(255),
    source VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX idx_recipes_user ON RECIPES(user_id);
CREATE INDEX idx_sessions_user ON BREW_SESSIONS(user_id);
CREATE INDEX idx_shared_expires ON SHARED_RECIPES(expires_at);
CREATE INDEX idx_metrics_event ON METRICS(event);
