package auth

import (
	"log"
	"os"

	"github.com/joho/godotenv"
)

type Config struct {
	SupabaseURL           string
	SupabaseAnonKey       string
	SupabaseServiceRole   string
	SupabaseJWTSecret     string
	OracleUser            string
	OraclePassword        string
	OracleConnectString   string
	OracleLibDir          string
}

func LoadConfig() *Config {
	// Try loading from root .env.local (generated by SOPS)
	// We check both local and parent directory
	_ = godotenv.Load(".env.local")
	_ = godotenv.Load("../.env.local")
	
	cfg := &Config{
		SupabaseURL:         os.Getenv("SUPABASE_URL"),
		SupabaseAnonKey:     os.Getenv("SUPABASE_ANON_KEY"),
		SupabaseServiceRole: os.Getenv("SUPABASE_SERVICE_ROLE_KEY"),
		SupabaseJWTSecret:   os.Getenv("SUPABASE_JWT_SECRET"),
		OracleUser:          os.Getenv("ORACLE_DB_USER"),
		OraclePassword:      os.Getenv("ORACLE_DB_PASSWORD"),
		OracleConnectString: os.Getenv("ORACLE_DB_CONNECT_STRING"),
		OracleLibDir:        os.Getenv("ORACLE_LIB_DIR"),
	}

	validateConfig(cfg)
	return cfg
}

func validateConfig(cfg *Config) {
	if cfg.SupabaseJWTSecret == "" {
		log.Println("WARNING: SUPABASE_JWT_SECRET is missing. Authentication middleware will fail.")
	}
	if cfg.OracleUser == "" || cfg.OraclePassword == "" {
		log.Println("WARNING: Oracle Database credentials are missing.")
	}
}
